### PR TITLE
Bumped Axios to 0.21.4

### PR DESCRIPTION
**Pull request by SrilalS**
https://www.npmjs.com/advisories/1594

### CODE REVIEW

**Comment by bogascorp** [comment]
This would be really helpful. My team is considering removing lottie due to the axios vulnerability.

**Comment by SrilalS** [comment]
@Ralph89 could you look into this?

**Comment by fczuardi** [comment]
@Ralph89 can you please publish a new version of the package to npm? I think the `@latest` (0.4.0) still lists the old axios as a dependency. Thanks!!

**Comment by fczuardi** [comment]
the workaround for now is to install directly from gthub, example:

```
yarn add SuperbuffNL/lottie-vuejs#85d89cfd6a0e81a3a20e01619bc46addbb7cbac0
```

**Pull request merged**
